package com.festive.poster.constant

enum class RecyclerViewActionType {
    POSTER_PACK_PURCHASED_CLICK,
    POSTER_TAP_TO_EDIT_CLICK,
    GET_POSTER_PACK_CLICK,
    POSTER_GREETING_MSG_CLICKED,
    POSTER_DOWNLOAD_CLICKED,
    BROWSE_TAB_POSTER_CAT_CLICKED
}