package com.festive.poster.reset

enum class TaskCode {
    GET_TEMPLATES,
    GET_TEMPLATE_CONFIG,
    UPLOAD_IMAGE,
    SAVE_KEY_VALUES,
    UPLOAD_USER_PROFILE_IMAGE,
    PUT_BIZ_MESSAGE_UPDATE,
    PUT_BIZ_MESSAGE_UPDATEV2,
    PUT_IMAGE_BIZ_UPDATE,
    PUT_IMAGE_BIZ_UPDATE_V2,
    GET_MERCHANT_SUMMARY,
    UPDATE_DRAFT,
    GET_CUSTOMER_DETAILS,
    GET_PAST_UPDATES_LIST;
}