package com.festive.poster.reset

enum class TaskCode {
    GET_TEMPLATES,
    GET_TEMPLATE_CONFIG,
    UPLOAD_IMAGE,
    SAVE_KEY_VALUES,
    UPLOAD_USER_PROFILE_IMAGE,
    PUT_BIZ_MESSAGE_UPDATE,
    PUT_IMAGE_BIZ_UPDATE,
    GET_MERCHANT_SUMMARY,
    GET_CUSTOMER_DETAILS
}