package com.appservice.model.product

import java.io.Serializable

data class ProductItemsResponseItem(
    val ApplicationId: Any,
    val BuyOnlineLink: Any,
    val CreatedOn: String,
    val CurrencyCode: String,
    val CustomWidgets: Any,
    val Description: String,
    val DiscountAmount: Double,
    val ExternalSourceId: Any,
    val FPTag: String,
    val GPId: Any,
    val GroupProductId: Any,
    val ImageUri: String,
    val Images: Any,
    val IsArchived: Boolean,
    val IsAvailable: Boolean,
    val IsFreeShipmentAvailable: Boolean,
    val MerchantName: Any,
    val Name: String,
    val Price: Double,
    val Priority: Int,
    val ProductIndex: Int,
    val ProductUrl: String,
    val ShipmentDuration: Int,
    val TileImageUri: String,
    val TotalQueries: Int,
    val UpdatedOn: String,
    val _id: String,
    val _keywords: Any,
    val availableUnits: Double,
    val brandName: String,
    val category: String,
    val gstSlab: Double,
    val hsnCode: Any,
    val isCodAvailable: Boolean,
    val isPrepaidOnlineAvailable: Boolean,
    val keySpecification: KeySpecification,
    val maxCodOrders: Int,
    val maxPrepaidOnlineOrders: Int,
    val otherSpecifications: List<Any>,
    val paymentType: String,
    val pickupAddressReferenceId: String,
    val productType: String,
    val tags: List<String>,
    val uniquePaymentUrl: UniquePaymentUrl,
    val variants: Boolean
):Serializable