package com.boost.presignin.constant

enum class IntentConstant {
  SESSION_DATA,
  POSITION,
  EXTRA_PHONE_NUMBER,
  EXTRA_BUSINESS_NAME,
  EXTRA_FP_LIST_AUTH,
  CATEGORY_DATA,
  CATEGORY_SUGG_UI,
  MOBILE_PREVIEW,
  DESKTOP_PREVIEW,
  WHATSAPP_CONSENT_FLAG
}