package com.boost.presignin.constant

object PreferenceConstant {
  const val NOW_FLOATS_PREFS = "nowfloatsPrefs"
  const val CLIENT_ID = "clientId"
  const val USER_PROFILE_ID = "user_profile_id"
  const val AUTHORIZATION = "Authorization"
  const val KEY_FP_ID = "fpid"
  const val CHANNEL_SHARE_URL = "channel_share_url"
  const val USER_ID = "user_id"
  const val PERSON_NAME = "person_name"
  const val PERSON_EMAIL = "person_email"
  const val KEY_sourceClientId = "source_clientid"
  const val GET_FP_EXPERIENCE_CODE = "GET_FP_EXPERIENCE_CODE"
  const val IS_USER_LOGIN = "IsUserLoggedIn"
  const val IS_UPDATE = "IsUpdate"
  const val WEBSITE_URL = "website_url"
  const val GET_FP_DETAILS_TAG = "GET_FP_DETAILS_TAG"
  const val IS_START_ACTIVITY = "IsStartActivity"
  const val KEY_FACEBOOK_PAGE = "facebookpage"
  const val KEY_FACEBOOK_NAME = "facebookname"
  const val FP_PAGE_SHARE_ENABLED = "fbPageShareEnabled"
  const val FP_PAGE_STATUS = "fbPageStatus"
  const val CONTACT_NAME = "contact_name"
  const val BUSINESS_NAME = "business_name"
  const val BUSINESS_IMAGE = "business_image"
  const val LOCATION = "location"
  const val BUSINESS_TYPE = "business_type"
  const val PRIMARY_NUMBER = "primary_number"
  const val PRIMARY_EMAIL = "primary_email"
}