package com.boost.presignin.constant

enum class RecyclerViewActionType {
  READING_SCORE_CLICK,
  CATEGORY_ITEM_CLICKED,
  BUSINESS_LIST_ITEM_CLICK,
  CATEGORY_SUGGESTION_CLICKED,
  INTRO_LOTTIE_ANIMATION_COMPLETE_INVOKE
}
