package com.appservice.rest

enum class TaskCode {
  POST_CREATE_SERVICE,
  GET_ACCOUNT_DETAILS,
  CREATE_ACCOUNT,
  UPDATE_ACCOUNT,
  IFSC_DETAIL,
  GET_KYC_DATA,
  GET_KYC_LIST_DATA,
  ADD_KYC_DATA,
  UPDATE_KYC_DATA,
  POST_FILE_UPLOAD

}