package com.appservice.rest

enum class TaskCode {
  POST_CREATE_SERVICE,
  POST_UPDATE_SERVICE,
  GET_ACCOUNT_DETAILS,
  CREATE_ACCOUNT,
  UPDATE_ACCOUNT,
  IFSC_DETAIL,
  GET_KYC_DATA,
  GET_KYC_LIST_DATA,
  ADD_KYC_DATA,
  UPDATE_KYC_DATA,
  POST_FILE_UPLOAD,
  PIC_UP_ADDRESS,
  ADD_UPDATE_IMAGE_PRODUCT_SERVICE,
  ADD_PRODUCT_GST_DETAIL,
  UPDATE_PRODUCT_GST_DETAIL,
  GET_PRODUCT_GST_DETAIL,
  UPLOAD_FILE_PRODUCT_IMAGE,
  ADD_PRODUCT_IMAGE,
  DELETE_PRODUCT_IMAGE,
  GET_PRODUCT_IMAGE,
  FP_ONBOARDING_UPDATE
}