package com.onboarding.nowfloats.constant

enum class FragmentType {
    CATEGORY_VIEW,
    CHANNEL_PICKER,
    REGISTRATION_BUSINESS_BASIC_DETAILS,
    REGISTRATION_BUSINESS_WEBSITE,
    REGISTRATION_BUSINESS_FACEBOOK_DETAILS,
    REGISTRATION_BUSINESS_TWITTER_DETAILS,
    REGISTRATION_BUSINESS_WHATSAPP,
    REGISTRATION_BUSINESS_API_CALL,
    REGISTRATION_COMPLETE
}