package com.onboarding.nowfloats.constant


enum class FragmentType {
  CATEGORY_VIEW,
  CHANNEL_PICKER,
  REGISTRATION_BUSINESS_BASIC_DETAILS,
  REGISTRATION_BUSINESS_WEBSITE,
  REGISTRATION_BUSINESS_GOOGLE_PAGE,
  REGISTRATION_BUSINESS_FACEBOOK_PAGE,
  REGISTRATION_BUSINESS_FACEBOOK_SHOP,
  REGISTRATION_BUSINESS_TWITTER_DETAILS,
  REGISTRATION_BUSINESS_WHATSAPP,
  REGISTRATION_BUSINESS_API_CALL,
  REGISTRATION_COMPLETE,
  MY_DIGITAL_CHANNEL;

  companion object {
    fun fromName(name: String?): FragmentType? =
      values().firstOrNull { it.name.equals(name, ignoreCase = true) }
  }
}