package com.onboarding.nowfloats.constant

enum class RecyclerViewActionType {
  CATEGORY_ITEM_CLICKED,
  FEATURE_ITEM_CLICKED,
  CHANNEL_ITEM_WHY_CLICKED,
  CHANNEL_ITEM_CLICKED,
  CITY_ITEM_CLICKED,
  CHANNEL_DISCONNECT_CLICKED,
  CHANNEL_CONNECT_CLICKED,
  CHANNEL_CONNECT_INFO_CLICKED,
  CHANNEL_DISCONNECT_WHY_CLICKED,
}
