package com.onboarding.nowfloats.rest

enum class Taskcode {
    GET_CHANNELS,
    GET_CATEGORIES,
    GET_FEATURES,

    POST_UPDATE_FACEBOOK_PAGE_TOKEN,
    POST_UPDATE_FACEBOOK_SHOP_TOKEN,
    POST_UPDATE_TWITTER_TOKEN,
    POST_UPDATE_GOOGLE_MY_BUSINESS_TOKEN,
    POST_CREATE_BUSINESS_ONBOARDING,
    POST_CREATE_BUSINESS_WHATSAPP,
    POST_CHECK_BUSINESS_DOMAIN,
    PUT_FILE_UPLOAD_IMAGE
}