package com.dashboard.rest

enum class TaskCode {
  POST_UPDATE_FACEBOOK_PAGE_TOKEN1,
  GET_BOOST_ADD_ONS,
  GET_BOOST_ADD_ONS_TOP,
  GET_USER_DETAIL_SHARE_DATA,
  GET_CUSTOMER_ITEM_DATA,
  GET_NAV_DASHBOARD_DATA,
  GET_QUICK_ACTION_DATA,
  GET_UPGRADE_PREMIUM_BANNER,
  GET_DOMAIN_DETAIL
}