package com.dashboard.rest

enum class TaskCode {
  POST_UPDATE_FACEBOOK_PAGE_TOKEN1,
  GET_BOOST_ADD_ONS,
  GET_BOOST_ADD_ONS_TOP,
  GET_WELCOME_DASHBOARD,
  GET_USER_DETAIL_SHARE_DATA,
  GET_CUSTOMER_ITEM_DATA,
  GET_WEBSITE_ITEM_DATA,
  GET_NAV_DASHBOARD_DATA,
  GET_DR_SCORE_UI_DATA,
  GET_QUICK_ACTION_DATA,
  GET_UPGRADE_PREMIUM_BANNER,
  GET_UPGRADE_DASHBOARD_BANNER,
  GET_DOMAIN_DETAIL,
  GET_SEARCH_ANALYTICS,
  GET_WEBSITE_CUSTOM_THEME,
  POST_UPDATE_WEBSITE_THEME,
  UPLOAD_BUSINESS_IMAGE,
  UPADTE_BUSINESS_PROFILE,
  MORE_SETTINGS,
  WEBSITE_NAV_DATA,
  UPDATE_BUSINESS_PROFILE,
  CAP_LIMIT_FEATURE_DETAILS,
  POST_REGISTER_RIA
}