package com.framework.webengageconstant

const val FLOATING_POINT_ID = "fpId"
const val NO_EVENT_VALUE = ""
const val NULL = ""
const val EVENT_VALUE_HOME_PAGE = "Home Page"
const val PLEASE_CHECK_YOUR_CREDENTIALS = "Please check your credentials"
const val FORGOT_PASSWORD_FAILED = "Forgot Password failed"
const val CLICKED = "Clicked"
const val EVENT_VALUE_MANAGE_CONTENT = "Manage content"
const val ADDONS_MARKETPLACE_ORDER_CONFIRMATION = "ADDONS MARKETPLACE ORDER CONFIRMATION"
const val ADDONS_MARKETPLACE_PAYMENT_SCREEN = "ADDONS MARKETPLACE PAYMENT SCREEN"
const val SKIP = "Skip"
const val YES = "Yes"
const val FAILED = "Failed"
const val TO_BE_ADDED = "To be added"