package com.framework.webengageconstant

const val BANK_ACCOUNT = "BANK ACCOUNT"
const val SERVICE_CATALOGUE_ADD_UPDATE = "SERVICE CATALOGUE ADD/UPDATE"
const val MANAGE_CONTENT = "MANAGE CONTENT"
const val KYC_VERIFICATION = "KYC VERIFICATION"
const val KYC_VERIFIED = "KYC verified"
const val PAGE_VIEW = "pageview"
const val SCREEN_NAME = "screen_name"
const val ADD_ONS = "Add-ons"
const val SITE_HEALTH = "SITE_HEALTH"
const val START_VIEW = "startview"
const val EVENT_LABEL_NULL = "null"
const val EVENT_LABEL_BIZ_KEYBOARD = "BIZ_KEYBOARD"
const val EVENT_LABEL_TESTIMONIAL_ADDED = "Testimonial added"
const val EVENT_LABEL_MANAGE_CONTENT = "MANAGE CONTENT"
const val EVENT_LABEL_DOMAIN_AND_EMAIL = "DOMAIN & EMAIL"
const val ORDER_ANALYTICS = "ORDER ANALYTICS"
const val NEWSLETTER_SUBSCRIPTIONS = "NEWSLETTER SUBSCRIPTIONS"
const val EVENT_LABEL_ADD_SUBSCRIBER = "Add: Subscriber"
const val ERROR_SUBSCRIBER = "Error: Subscriber"
const val BUSINESS_PROFILE = "BUSINESS PROFILE"
const val CLICKING_USE_SAME_TIME_FOR_WHOLE_WEEK = "Clicking: Use same time for whole week"
const val TOGGLE_SUNDAY = "Toggle: Sunday"
const val TOGGLE_MONDAY = "Toggle: MONDAY"
const val TOGGLE_TUESDAY = "Toggle: TUESDAY"
const val TOGGLE_WEDNESDAY = "Toggle: WEDNESDAY"
const val TOGGLE_THURSDAY = "Toggle: THURSDAY"
const val TOGGLE_FRIDAY = "Toggle: FRIDAY"
const val TOGGLE_SATURDAY = "Toggle: SATURDAY"


