package com.dashboard.constant

enum class FragmentType {
  DIGITAL_READINESS_SCORE,
  FRAGMENT_WEBSITE_THEME,
  FRAGMENT_BUSINESS_PROFILE,
  ALL_BOOST_ADD_ONS,
  CONSULTATION_HOURS,
  CREATE_DOCTOR_PROFILE,
  OWNER_INFO,
  DOCTOR_ADDITIONAL_INFO
}