package com.dashboard.constant

enum class IntentConstant {
  SESSION_DATA,
  POSITION,
  FONT_LIST_PRIMARY,
  FONT_LIST_SECONDARY,
  COLOR_LIST,
  FONT_LIST,
  BUSINESS_DETAILS
  SESSION_DATA,FPTAG,
  POSITION,;


}