package com.dashboard.constant

enum class RecyclerViewActionType {
  READING_SCORE_CLICK,
  BUSINESS_UPDATE_CLICK,
  ROI_SUMMARY_CLICK,
  GROWTH_STATS_CLICK,
  BUSINESS_SETUP_SCORE_CLICK,
  BUSINESS_SETUP_ADD_ITEM_START,
  NAV_CLICK_ITEM_CLICK,
  QUICK_ACTION_ITEM_CLICK,
  BUSINESS_ADD_ONS_CLICK,
  CHANNEL_ITEM_CLICK,
  CUSTOMER_PATIENT_ITEM_CLICK,
  WEBSITE_ITEM_CLICK,
  DIGITAL_SCORE_READINESS_CLICK,
  PROMO_BANNER_CLICK,
  PROMO_BOOST_ACADEMY_CLICK,
  CHANNEL_ACTIVATE_CLICK,
  ITEM_COLOR_CLICK,
  PRIMARY_FONT_SELECTED,
  SECONDARY_FONT_SELECTED,
  DATE_FILTER_CLICK,
  TOGGLE_STATE_CHANGED,
  CHECK_BOX_APPLY_ALL,
  ADD_SESSION
}
