package com.dashboard.constant

enum class RecyclerViewActionType {
  READING_SCORE_CLICK,
  BUSINESS_UPDATE_CLICK,
  ROI_SUMMARY_CLICK,
  GROWTH_STATS_CLICK,
  BUSINESS_SETUP_SCORE_CLICK,
  NAV_CLICK_ITEM_CLICK,
  QUICK_ACTION_ITEM_CLICK,
  BUSINESS_ADD_ONS_CLICK,
  CHANNEL_ITEM_CLICK,
  CUSTOMER_PATIENT_ITEM_CLICK,
  DIGITAL_SCORE_READINESS_CLICK,
  PROMO_BANNER_CLICK,
  PROMO_BOOST_ACADEMY_CLICK,
}
