package com.appservice.constant

enum class FragmentType {
  SERVICE_DETAIL_VIEW,
  SERVICE_INFORMATION,
  ADD_BANK_ACCOUNT_START,
  BANK_ACCOUNT_DETAILS,
  PAYMENT_GATEWAY,
  SCAN_PAN_CARD,
  KYC_DETAILS,
  PAYMENT_DOCS_SUBMITTED,
  PAYMENT_DOCS_UNDER_VERIFICATION,
  PAYMENT_DOCS_VERIFICATION_FAILED,
  PAYMENT_DOCS_VERIFICATION_SUCCESS,
  KYC_STATUS
}