package com.appservice.constant

enum class FragmentType {
  BUSINESS_KYC_VIEW,
  SERVICE_DETAIL_VIEW,
  SERVICE_INFORMATION,
  DETAIL_KYC_VIEW,
  ADD_BANK_ACCOUNT_START,
  BANK_ACCOUNT_DETAILS,
  PAYMENT_GATEWAY,
  SCAN_PAN_CARD,
  KYC_DETAILS,
  KYC_STATUS,
  CROP_IMAGE,
  KYC_DETAIL_NEW,
}