package com.appservice.constant

enum class IntentConstant {
  IS_UPDATED,
  CLIENT_ID,
  USER_PROFILE_ID,
  FP_ID,
  FP_TAG,
  EXPERIENCE_CODE,
  FP_LOGO,
  FP_USER_EMAIL,
  FP_USER_NUMBER,
  SESSION_DATA,
  CUSTOM_PAYMENT_GATEWAY,
  PAN_CARD_IMAGE,
  KYC_DETAIL
}