package com.appservice.constant

object PreferenceConstant {
  const val NOW_FLOATS_PREFS = "nowfloatsPrefs"
  const val CLIENT_ID = "clientId"
  const val USER_PROFILE_ID = "user_profile_id"
  const val AUTHORIZATION = "Authorization"
  const val KEY_FP_ID = "fpid"
  const val GET_FP_DETAILS_TAG = "GET_FP_DETAILS_TAG"
  const val GET_FP_EXPERIENCE_CODE = "GET_FP_EXPERIENCE_CODE"
  const val GET_FP_WEBTEMPLATE_ID = "GET_FP_WEBTEMPLATE_ID"
  const val KEY_sourceClientId = "source_clientid"

  const val IS_ACCOUNT_SAVE = "isAccountSave"
  const val IS_SELF_BRANDED_KYC_ADD = "isSelfBrandedKycAdd"

  const val GET_FP_DETAILS_SUNDAY_START_TIME = "GET_FP_DETAILS_SUNDAY_START_TIME"
  const val GET_FP_DETAILS_SUNDAY_END_TIME = "GET_FP_DETAILS_SUNDAY_END_TIME"
  const val GET_FP_DETAILS_MONDAY_START_TIME = "GET_FP_DETAILS_MONDAY_START_TIME"
  const val GET_FP_DETAILS_MONDAY_END_TIME = "GET_FP_DETAILS_MONDAY_END_TIME"
  const val GET_FP_DETAILS_TUESDAY_START_TIME = "GET_FP_DETAILS_TUESDAY_START_TIME"
  const val GET_FP_DETAILS_TUESDAY_END_TIME = "GET_FP_DETAILS_TUESDAY_END_TIME"
  const val GET_FP_DETAILS_WEDNESDAY_START_TIME = "GET_FP_DETAILS_WEDNESDAY_START_TIME"
  const val GET_FP_DETAILS_WEDNESDAY_END_TIME = "GET_FP_DETAILS_WEDNESDAY_END_TIME"
  const val GET_FP_DETAILS_THURSDAY_START_TIME = "GET_FP_DETAILS_THURSDAY_START_TIME"
  const val GET_FP_DETAILS_THURSDAY_END_TIME = "GET_FP_DETAILS_THURSDAY_END_TIME"
  const val GET_FP_DETAILS_FRIDAY_START_TIME = "GET_FP_DETAILS_FRIDAY_START_TIME"
  const val GET_FP_DETAILS_FRIDAY_END_TIME = "GET_FP_DETAILS_FRIDAY_END_TIME"
  const val GET_FP_DETAILS_SATURDAY_START_TIME = "GET_FP_DETAILS_SATURDAY_START_TIME"
  const val GET_FP_DETAILS_SATURDAY_END_TIME = "GET_FP_DETAILS_SATURDAY_END_TIME"
}