package com.appservice.constant

enum class RecyclerViewActionType {
  ORDER_SUMMARY_CLICKED,
  IMAGE_CLEAR_CLICK, IMAGE_CHANGE,
  UPDATE_SPECIFICATION_VALUE,
  CLEAR_SPECIFICATION_CLICK,
  GST_DETAIL_CLICK,
  TOGGLE_STATE_CHANGED,
  CHECK_BOX_APPLY_ALL,
  ADD_SESSION,
  CHANGE_SERVICE_TIMING,
  SERVICE_ITEM_CLICK,
  PRODUCT_ITEM_CLICK,
  PRODUCT_DATA_SHARE_CLICK,
  SESSION_ITEM_CLICK,
  STAFF_LISTING_CLICK,
  STAFF_FILTER_CLICK,
  STAFF_EXPERIENCE_CLICK,
  SERVICE_DATA_SHARE_CLICK,
  SERVICE_WHATS_APP_SHARE,
  UPDATE_WHATS_APP_SHARE,
  UPDATE_OTHER_SHARE,
  UPDATE_FP_APP_SHARE,
  UPDATE_BUSINESS_CLICK,
  OFFER_DATA_SHARE_CLICK,
  OFFER_ITEM_CLICK,
  OFFER_WHATS_APP_SHARE,
  CREATE_CATEGORY_MENU_CLICK
  SERVICE_WHATS_APP_SHARE,
  PRODUCT_WHATS_APP_SHARE,
  CREATE_CATEGORY_MENU_CLICK, ON_SELECT_CATEGORY
}
