package com.appservice.constant

enum class RecyclerViewActionType {
  ORDER_SUMMARY_CLICKED,
  IMAGE_CLEAR_CLICK,
  UPDATE_SPECIFICATION_VALUE,
  CLEAR_SPECIFICATION_CLICK,
  GST_DETAIL_CLICK,
  TOGGLE_STATE_CHANGED,
  CHECK_BOX_APPLY_ALL,
  ADD_SESSION,
  SERVICE_ITEM_CLICK,
  SESSION_ITEM_CLICK,
  STAFF_LISTING_CLICK,
  STAFF_FILTER_CLICK,
  STAFF_EXPERIENCE_CLICK, SERVICE_DATA_SHARE_CLICK, SERVICE_WHATS_APP_SHARE
}
