package com.inventoryorder.model.product

import java.io.Serializable

data class Product(
    val ApplicationId: Any? = null,
    val BuyOnlineLink: String? = null,
    val CreatedOn: String? = null,
    val CurrencyCode: String? = null,
    val CustomWidgets: Any? = null,
    val Description: String? = null,
    val DiscountAmount: Double? = null,
    val ExternalSourceId: Any? = null,
    val FPTag: String? = null,
    val GPId: Any? = null,
    val GroupProductId: Any? = null,
    val ImageUri: String? = null,
    val Images: Any? = null,
    val IsArchived: Boolean? = null,
    val IsAvailable: Boolean? = null,
    val IsFreeShipmentAvailable: Boolean? = null,
    val MerchantName: Any? = null,
    val Name: String? = null,
    val Price: Double? = null,
    val Priority: Int? = null,
    val ProductIndex: Int? = null,
    val ProductUrl: String? = null,
    val ShipmentDuration: Int? = null,
    val TileImageUri: String? = null,
    val TotalQueries: Int? = null,
    val UpdatedOn: String? = null,
    val _id: String? = null,
    val _keywords: Any? = null,
    val availableUnits: Double? = null,
    val brandName: Any? = null,
    val category: String? = null,
    val isCodAvailable: Boolean? = null,
    val isPrepaidOnlineAvailable: Boolean? = null,
    val keySpecification: Any? = null,
    val maxCodOrders: Int? = null,
    val maxPrepaidOnlineOrders: Int? = null,
    val otherSpecifications: List<Any>? = null,
    val paymentType: String? = null,
    val pickupAddressReferenceId: Any? = null,
    var productType: String? = null,
    val tags: List<String>? = null,
    val uniquePaymentUrl: Any? = null,
    val variants: Boolean? = null
):Serializable

