/*
 * Copyright 2016 Hani Al Momani
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.android.inputmethod.keyboard.emoji.models;

/**
 * @author Hani Al Momani (hani.momanii@gmail.com)
 */
public class Nature {
    public static final String[] DATA = new String[]{

            Emojicon.fromCodePointString(0x1f436),
            Emojicon.fromCodePointString(0x1f431),
            Emojicon.fromCodePointString(0x1f42d),
            Emojicon.fromCodePointString(0x1f439),
            Emojicon.fromCodePointString(0x1f430),
            Emojicon.fromCodePointString(0x1f43b),
            Emojicon.fromCodePointString(0x1f43c),
            Emojicon.fromCodePointString(0x1f428),
            Emojicon.fromCodePointString(0x1f42f),
            Emojicon.fromCodePointString(0x1f981),
            Emojicon.fromCodePointString(0x1f42e),
            Emojicon.fromCodePointString(0x1f437),
            Emojicon.fromCodePointString(0x1f43d),
            Emojicon.fromCodePointString(0x1f438),
            Emojicon.fromCodePointString(0x1f419),
            Emojicon.fromCodePointString(0x1f435),
            Emojicon.fromCodePointString(0x1f648),
            Emojicon.fromCodePointString(0x1f649),
            Emojicon.fromCodePointString(0x1f64a),
            Emojicon.fromCodePointString(0x1f412),
            Emojicon.fromCodePointString(0x1f414),
            Emojicon.fromCodePointString(0x1f427),
            Emojicon.fromCodePointString(0x1f426),
            Emojicon.fromCodePointString(0x1f424),
            Emojicon.fromCodePointString(0x1f423),
            Emojicon.fromCodePointString(0x1f425),
            Emojicon.fromCodePointString(0x1f43a),
            Emojicon.fromCodePointString(0x1f417),
            Emojicon.fromCodePointString(0x1f434),
            Emojicon.fromCodePointString(0x1f984),
            Emojicon.fromCodePointString(0x1f41d),
            Emojicon.fromCodePointString(0x1f41b),
            Emojicon.fromCodePointString(0x1f40c),
            Emojicon.fromCodePointString(0x1f41e),
            Emojicon.fromCodePointString(0x1f41c),
            Emojicon.fromCodePointString(0x1f577),
            Emojicon.fromCodePointString(0x1f982),
            Emojicon.fromCodePointString(0x1f980),
            Emojicon.fromCodePointString(0x1f40d),
            Emojicon.fromCodePointString(0x1f422),
            Emojicon.fromCodePointString(0x1f420),
            Emojicon.fromCodePointString(0x1f41f),
            Emojicon.fromCodePointString(0x1f421),
            Emojicon.fromCodePointString(0x1f42c),
            Emojicon.fromCodePointString(0x1f433),
            Emojicon.fromCodePointString(0x1f40b),
            Emojicon.fromCodePointString(0x1f40a),
            Emojicon.fromCodePointString(0x1f406),
            Emojicon.fromCodePointString(0x1f405),
            Emojicon.fromCodePointString(0x1f403),
            Emojicon.fromCodePointString(0x1f402),
            Emojicon.fromCodePointString(0x1f404),
            Emojicon.fromCodePointString(0x1f42a),
            Emojicon.fromCodePointString(0x1f42b),
            Emojicon.fromCodePointString(0x1f418),
            Emojicon.fromCodePointString(0x1f410),
            Emojicon.fromCodePointString(0x1f40f),
            Emojicon.fromCodePointString(0x1f411),
            Emojicon.fromCodePointString(0x1f40e),
            Emojicon.fromCodePointString(0x1f416),
            Emojicon.fromCodePointString(0x1f400),
            Emojicon.fromCodePointString(0x1f401),
            Emojicon.fromCodePointString(0x1f413),
            Emojicon.fromCodePointString(0x1f983),
            Emojicon.fromCodePointString(0x1f54a),
            Emojicon.fromCodePointString(0x1f415),
            Emojicon.fromCodePointString(0x1f429),
            Emojicon.fromCodePointString(0x1f408),
            Emojicon.fromCodePointString(0x1f407),
            Emojicon.fromCodePointString(0x1f43f),
            Emojicon.fromCodePointString(0x1f43e),
            Emojicon.fromCodePointString(0x1f409),
            Emojicon.fromCodePointString(0x1f432),
            Emojicon.fromCodePointString(0x1f335),
            Emojicon.fromCodePointString(0x1f332),
            Emojicon.fromCodePointString(0x1f333),
            Emojicon.fromCodePointString(0x1f334),
            Emojicon.fromCodePointString(0x1f33f),
            Emojicon.fromCodePointString(0x1f340),
            Emojicon.fromCodePointString(0x1f38d),
            Emojicon.fromCodePointString(0x1f38b),
            Emojicon.fromCodePointString(0x1f343),
            Emojicon.fromCodePointString(0x1f342),
            Emojicon.fromCodePointString(0x1f341),
            Emojicon.fromCodePointString(0x1f33e),
            Emojicon.fromCodePointString(0x1f33a),
            Emojicon.fromCodePointString(0x1f33b),
            Emojicon.fromCodePointString(0x1f339),
            Emojicon.fromCodePointString(0x1f337),
            Emojicon.fromCodePointString(0x1f33c),
            Emojicon.fromCodePointString(0x1f338),
            Emojicon.fromCodePointString(0x1f490),
            Emojicon.fromCodePointString(0x1f344),
            Emojicon.fromCodePointString(0x1f330),
            Emojicon.fromCodePointString(0x1f383),
            Emojicon.fromCodePointString(0x1f41a),
            Emojicon.fromCodePointString(0x1f578),
            Emojicon.fromCodePointString(0x1f30d),
            Emojicon.fromCodePointString(0x1f30e),
            Emojicon.fromCodePointString(0x1f30f),
            Emojicon.fromCodePointString(0x1f315),
            Emojicon.fromCodePointString(0x1f316),
            Emojicon.fromCodePointString(0x1f317),
            Emojicon.fromCodePointString(0x1f318),
            Emojicon.fromCodePointString(0x1f311),
            Emojicon.fromCodePointString(0x1f312),
            Emojicon.fromCodePointString(0x1f313),
            Emojicon.fromCodePointString(0x1f314),
            Emojicon.fromCodePointString(0x1f31a),
            Emojicon.fromCodePointString(0x1f31d),
            Emojicon.fromCodePointString(0x1f31b),
            Emojicon.fromCodePointString(0x1f31c),
            Emojicon.fromCodePointString(0x1f31e),
            Emojicon.fromCodePointString(0x1f319),
            Emojicon.fromCodePointString(0x1f324),
            Emojicon.fromCodePointString(0x1f325),
            Emojicon.fromCodePointString(0x1f326),
            Emojicon.fromCodePointString(0x1f327),
            Emojicon.fromCodePointString(0x1f329),
            Emojicon.fromCodePointString(0x1f4a5),
            Emojicon.fromCodePointString(0x1f328),
            Emojicon.fromCodePointString(0x1f32c),
            Emojicon.fromCodePointString(0x1f4a8),
            Emojicon.fromCodePointString(0x1f32a),
            Emojicon.fromCodePointString(0x1f32b),
            Emojicon.fromCodePointString(0x1f4a6),
            Emojicon.fromCodePointString(0x1f4a7),
            Emojicon.fromCodePointString(0x1f30a),


            /*Emojicon.fromCodePointString(0x1f436),
            Emojicon.fromCodePointString(0x1f43a),
            Emojicon.fromCodePointString(0x1f431),
            Emojicon.fromCodePointString(0x1f42d),
            Emojicon.fromCodePointString(0x1f439),
            Emojicon.fromCodePointString(0x1f430),
            Emojicon.fromCodePointString(0x1f438),
            Emojicon.fromCodePointString(0x1f42f),
            Emojicon.fromCodePointString(0x1f428),
            Emojicon.fromCodePointString(0x1f43b),
            Emojicon.fromCodePointString(0x1f437),
            Emojicon.fromCodePointString(0x1f43d),
            Emojicon.fromCodePointString(0x1f42e),
            Emojicon.fromCodePointString(0x1f417),
            Emojicon.fromCodePointString(0x1f435),
            Emojicon.fromCodePointString(0x1f412),
            Emojicon.fromCodePointString(0x1f434),
            Emojicon.fromCodePointString(0x1f411),
            Emojicon.fromCodePointString(0x1f418),
            Emojicon.fromCodePointString(0x1f43c),
            Emojicon.fromCodePointString(0x1f427),
            Emojicon.fromCodePointString(0x1f426),
            Emojicon.fromCodePointString(0x1f424),
            Emojicon.fromCodePointString(0x1f425),
            Emojicon.fromCodePointString(0x1f423),
            Emojicon.fromCodePointString(0x1f414),
            Emojicon.fromCodePointString(0x1f40d),
            Emojicon.fromCodePointString(0x1f422),
            Emojicon.fromCodePointString(0x1f41b),
            Emojicon.fromCodePointString(0x1f41d),
            Emojicon.fromCodePointString(0x1f41c),
            Emojicon.fromCodePointString(0x1f41e),
            Emojicon.fromCodePointString(0x1f40c),
            Emojicon.fromCodePointString(0x1f419),
            Emojicon.fromCodePointString(0x1f41a),
            Emojicon.fromCodePointString(0x1f420),
            Emojicon.fromCodePointString(0x1f41f),
            Emojicon.fromCodePointString(0x1f42c),
            Emojicon.fromCodePointString(0x1f433),
            Emojicon.fromCodePointString(0x1f40b),
            Emojicon.fromCodePointString(0x1f404),
            Emojicon.fromCodePointString(0x1f40f),
            Emojicon.fromCodePointString(0x1f400),
            Emojicon.fromCodePointString(0x1f403),
            Emojicon.fromCodePointString(0x1f405),
            Emojicon.fromCodePointString(0x1f407),
            Emojicon.fromCodePointString(0x1f409),
            Emojicon.fromCodePointString(0x1f40e),
            Emojicon.fromCodePointString(0x1f410),
            Emojicon.fromCodePointString(0x1f413),
            Emojicon.fromCodePointString(0x1f415),
            Emojicon.fromCodePointString(0x1f416),
            Emojicon.fromCodePointString(0x1f401),
            Emojicon.fromCodePointString(0x1f402),
            Emojicon.fromCodePointString(0x1f432),
            Emojicon.fromCodePointString(0x1f421),
            Emojicon.fromCodePointString(0x1f40a),
            Emojicon.fromCodePointString(0x1f42b),
            Emojicon.fromCodePointString(0x1f42a),
            Emojicon.fromCodePointString(0x1f406),
            Emojicon.fromCodePointString(0x1f408),
            Emojicon.fromCodePointString(0x1f429),
            Emojicon.fromCodePointString(0x1f43e),
            Emojicon.fromCodePointString(0x1f490),
            Emojicon.fromCodePointString(0x1f338),
            Emojicon.fromCodePointString(0x1f337),
            Emojicon.fromCodePointString(0x1f340),
            Emojicon.fromCodePointString(0x1f339),
            Emojicon.fromCodePointString(0x1f33b),
            Emojicon.fromCodePointString(0x1f33a),
            Emojicon.fromCodePointString(0x1f341),
            Emojicon.fromCodePointString(0x1f343),
            Emojicon.fromCodePointString(0x1f342),
            Emojicon.fromCodePointString(0x1f33f),
            Emojicon.fromCodePointString(0x1f33e),
            Emojicon.fromCodePointString(0x1f344),
            Emojicon.fromCodePointString(0x1f335),
            Emojicon.fromCodePointString(0x1f334),
            Emojicon.fromCodePointString(0x1f332),
            Emojicon.fromCodePointString(0x1f333),
            Emojicon.fromCodePointString(0x1f330),
            Emojicon.fromCodePointString(0x1f331),
            Emojicon.fromCodePointString(0x1f33c),
            Emojicon.fromCodePointString(0x1f310),
            Emojicon.fromCodePointString(0x1f31e),
            Emojicon.fromCodePointString(0x1f31d),
            Emojicon.fromCodePointString(0x1f31a),
            Emojicon.fromCodePointString(0x1f311),
            Emojicon.fromCodePointString(0x1f312),
            Emojicon.fromCodePointString(0x1f313),
            Emojicon.fromCodePointString(0x1f314),
            Emojicon.fromCodePointString(0x1f315),
            Emojicon.fromCodePointString(0x1f316),
            Emojicon.fromCodePointString(0x1f317),
            Emojicon.fromCodePointString(0x1f318),
            Emojicon.fromCodePointString(0x1f31c),
            Emojicon.fromCodePointString(0x1f31b),
            Emojicon.fromCodePointString(0x1f319),
            Emojicon.fromCodePointString(0x1f30d),
            Emojicon.fromCodePointString(0x1f30e),
            Emojicon.fromCodePointString(0x1f30f),
            Emojicon.fromCodePointString(0x1f30b),
            Emojicon.fromCodePointString(0x1f30c),
            Emojicon.fromCodePointString(0x1f320),
            Emojicon.fromChar((char) 0x2b50),
            Emojicon.fromChar((char) 0x2600),
            Emojicon.fromChar((char) 0x26c5),
            Emojicon.fromChar((char) 0x2601),
            Emojicon.fromChar((char) 0x26a1),
            Emojicon.fromChar((char) 0x2614),
            Emojicon.fromChar((char) 0x2744),
            Emojicon.fromChar((char) 0x26c4),
            Emojicon.fromCodePointString(0x1f300),
            Emojicon.fromCodePointString(0x1f301),
            Emojicon.fromCodePointString(0x1f308),
            Emojicon.fromCodePointString(0x1f30a),*/
    };
}
