package com.boost.presignin.rest

enum class TaskCode {
  POST_UPDATE_FACEBOOK_PAGE_TOKEN1,
  GET_CATEGORIES,
  CHECK_MOBILE_IS_REGISTERED,
  CONNECT_USER_PROFILE,
  CREATE_USER_PROFILE,
  VERIFY_USER_PROFILE,
  GET_FP_DETAILS_BY_PHONE,
  VERIFY_OTP,
  SEND_OTP_INDIA,
  GET_FP_LIST_FOR_REGISTERED_NUMBER,
  GET_FP_USER_DETAILS
}