package com.inventoryorder.constant

enum class FragmentType {
  ALL_ORDER_VIEW,
  ORDER_DETAIL_VIEW,
  ORDER_INVOICE_VIEW,
  ALL_APPOINTMENT_VIEW,
  APPOINTMENT_DETAIL_VIEW,
  CREATE_NEW_BOOKING,
  CREATE_NEW_BOOKING_PAGE_2,
  BOOKING_SUCCESSFUL,
  ALL_VIDEO_CONSULT_VIEW,
  VIDEO_CONSULT_DETAIL_VIEW,
  CREATE_APPOINTMENT_VIEW,
  CREATE_NEW_ORDER,
  ADD_CUSTOMER,
  ADD_PRODUCT,
  BILLING_DETAIL,
  ORDER_PLACED
}
