package com.inventoryorder.constant

enum class IntentConstant {
  PREFERENCE_DATA,
  ORDER_ITEM,
  ORDER_ID,
  IS_VIDEO,
  EXPERIENCE_CODE,
  BOOKING_ITEM,
  IS_REFRESH,
  RESULT_DATA,
  ORDER_REQUEST,
  TOTAL_PRICE,
  DISCOUNTED_PRICE,
  CURRENCY,
  SHOULD_FINISH,
  ADD_MORE_ITEM,
  SHOULD_RE_INITIATE,
  CREATE_ORDER_RESPONSE,
  SELECTED_SERVICE,
  TYPE_APPOINTMENT, VIDEO_ITEM
}