package com.inventoryorder.constant

enum class RecyclerViewActionType {
  ORDER_SUMMARY_CLICKED,
  ORDER_ITEM_CLICKED,
  ORDER_BUTTON_CLICKED,
  ORDER_DROPDOWN_CLICKED,
  DELIVERY_ITEM_CLICKED,
  BOOKING_ITEM_CLICKED,
  BOOKING_CONFIRM_CLICKED,
  ALL_BOOKING_ITEM_CLICKED,
  VIDEO_CONSULT_ITEM_CLICKED,
  VIDEO_CONSULT_CALL_CLICKED,
  VIDEO_CONSULT_COPY_CLICKED,
  APPOINTMENT_ITEM_CLICKED,
  GENDER_SELECT_ITEM,
  CHOOSE_PURPOSE_ITEM,
  PICK_INVENTORY_NATURE,
  APPOINTMENT_SCHEDULE,
  FILTER_ACTION_ITEM,
  BUTTON_ACTION_ITEM,
  TIME_SLOT_ACTION_ITEM
}
