package com.inventoryorder.constant

enum class RecyclerViewActionType {
  ORDER_SUMMARY_CLICKED,
  ORDER_ITEM_CLICKED,
  ORDER_CONFIRM_CLICKED,
  DELIVERY_ITEM_CLICKED,
  BOOKING_ITEM_CLICKED,
  BOOKING_CONFIRM_CLICKED,
  ALL_BOOKING_ITEM_CLICKED,
  APPOINTMENT_ITEM_CLICKED,
  GENDER_SELECT_ITEM,
  CHOOSE_PURPOSE_ITEM

}
