package com.inventoryorder.rest

enum class TaskCode {
  GET_SELLER_SUMMARY,
  GET_LIST_ORDER,
  GET_LIST_ORDER_FILTER,
  GET_ASSURE_PURCHASE_ORDER,
  GET_LIST_CANCELLED_ORDER,
  GET_ORDER_DETAILS,
  GET_LIST_IN_COMPLETE_ORDER,
  CONFIRM_ORDER_TASK,
  CANCEL_ORDER_TASK,
  PRODUCT_ORDER_DETAILS_TASK,
  GET_ALL_SERVICES,
  GET_DOCTOR_DATA,
  POST_ORDER_INITIATE,
  GET_DOCTOR_WEEKLY_SCHEDULE,
  GET_DOCTOR_API_DATA,
  ADD_API_CONSULT_DATA,

}