package com.inventoryorder.rest

enum class Taskcode {
  GET_SELLER_SUMMARY,
  GET_LIST_ORDER,
  GET_ASSURE_PURCHASE_ORDER,
  GET_LIST_CANCELLED_ORDER,
  GET_LIST_IN_COMPLETE_ORDER,
  CONFIRM_ORDER_TASK,
  CANCEL_ORDER_TASK

}