package com.boost.dbcenterapi.recycleritem

enum class RecyclerViewItemType {
  PAGINATION_LOADER,
  PROMO_BANNER,
  FEATURES_BY_CATEGORY,
  PACKS,
  VIDEOS,
  PARTNER,
  MARKETPLACE_OFFERS,
  FEATURES_MODEL,
  RESULT,
  PACKS_BUNDLES,
  FEATURE_DETAILS,
  TOP_FEATURES,
  SECONDARY_IMAGES;
}
