package com.boost.marketplace.constant

enum class FragmentType {
  DIGITAL_READINESS_SCORE,
  ALL_BOOST_ADD_ONS,
  FRAGMENT_WEBSITE_THEME,
  FRAGMENT_BUSINESS_PROFILE,
  CONSULTATION_HOURS,
  CREATE_DOCTOR_PROFILE,
  OWNER_INFO,
  DOCTOR_ADDITIONAL_INFO,
  FRAGMENT_WEBSITE_NAV,
  FRAGMENT_USER_PROFILE,
  FRAGMENT_USER_PROFILE_IMAGE_CROP
}