package com.boost.marketplace.constant

enum class RecyclerViewActionType {

  BUSINESS_ADD_ONS_CLICK,
  MARKETPLACE_PROMO_BANNER_CLICK,
  FEATURES_BY_CATEGORY_CLICK,
  PARTNER_CLICK,
  PACKS_CLICK,
  TOP_FEATURES_CLICK,
  SECONDARY_IMAGE_CLICK,
  MY_PLAN_PREMIUM_CLICK
}
